name: "fibonnaci  Action"
description: "fibonnaci  Action"
author: "jmcamelo@uninorte.edu.co"

inputs:
    MY_num:
        description: "fibonnaci action"

    runs:
        using: "docker"
        image: "Dockerfile"
